"""initial_schema

Revision ID: b404659b8ee6
Revises:
Create Date: 2026-07-16 19:07:12.669641
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b404659b8ee6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("home_location", sa.String(length=500), nullable=True),
        sa.Column("home_latitude", sa.Float(), nullable=True),
        sa.Column("home_longitude", sa.Float(), nullable=True),
        sa.Column("cv_filename", sa.String(length=500), nullable=True),
        sa.Column("cv_text", sa.Text(), nullable=True),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("base_url", sa.String(length=1000), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("free_api", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("run_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovered_count", sa.Integer(), nullable=False),
        sa.Column("fetched_count", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("lock_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crawl_runs_source_id"), "crawl_runs", ["source_id"], unique=False)
    op.create_index(
        "ix_crawl_runs_status_created", "crawl_runs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "job_postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("canonical_url", sa.String(length=2000), nullable=True),
        sa.Column("canonical_key", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("employer", sa.String(length=500), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=False),
        sa.Column("location_text", sa.String(length=1000), nullable=True),
        sa.Column("postcode", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=200), nullable=True),
        sa.Column("state", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("remote_type", sa.String(length=40), nullable=True),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column("contract_type", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_job_source_external"),
    )
    op.create_index(
        op.f("ix_job_postings_content_hash"), "job_postings", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_job_postings_contract_type"), "job_postings", ["contract_type"], unique=False
    )
    op.create_index(op.f("ix_job_postings_employer"), "job_postings", ["employer"], unique=False)
    op.create_index(
        op.f("ix_job_postings_employment_type"), "job_postings", ["employment_type"], unique=False
    )
    op.create_index(
        op.f("ix_job_postings_published_at"), "job_postings", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_postings_remote_type"), "job_postings", ["remote_type"], unique=False
    )
    op.create_index(op.f("ix_job_postings_source_id"), "job_postings", ["source_id"], unique=False)
    op.create_index(op.f("ix_job_postings_state"), "job_postings", ["state"], unique=False)
    op.create_index(
        "ix_jobs_active_published", "job_postings", ["is_active", "published_at"], unique=False
    )
    op.create_index("ix_jobs_canonical_key", "job_postings", ["canonical_key"], unique=False)
    op.create_index("ix_jobs_state_city", "job_postings", ["state", "city"], unique=False)
    op.create_table(
        "preference_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_profile_id", sa.Integer(), nullable=True),
        sa.Column("employment_types", sa.JSON(), nullable=False),
        sa.Column("contract_types", sa.JSON(), nullable=False),
        sa.Column("preferred_states", sa.JSON(), nullable=False),
        sa.Column("include_germany_remote", sa.Boolean(), nullable=False),
        sa.Column("commute_penalty_minutes", sa.Integer(), nullable=False),
        sa.Column("max_commute_minutes", sa.Integer(), nullable=False),
        sa.Column("onsite_weight", sa.Float(), nullable=False),
        sa.Column("hybrid_weight", sa.Float(), nullable=False),
        sa.Column("remote_weight", sa.Float(), nullable=False),
        sa.Column("min_salary", sa.Integer(), nullable=True),
        sa.Column("target_salary", sa.Integer(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("role_terms", sa.JSON(), nullable=False),
        sa.Column("extra_preferences", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"], ["candidate_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preference_profiles_candidate_profile_id"),
        "preference_profiles",
        ["candidate_profile_id"],
        unique=True,
    )
    op.create_table(
        "application_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("documents", sa.JSON(), nullable=False),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interview_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offer_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_records_job_id"), "application_records", ["job_id"], unique=True
    )
    op.create_index(
        op.f("ix_application_records_status"), "application_records", ["status"], unique=False
    )
    op.create_table(
        "feedback_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=True),
        sa.Column("weight_delta", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_events_job_id"), "feedback_events", ["job_id"], unique=False)
    op.create_table(
        "job_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("candidate_profile_id", sa.Integer(), nullable=True),
        sa.Column("profile_version", sa.Integer(), nullable=True),
        sa.Column("preference_version", sa.Integer(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("candidate_fit_score", sa.Float(), nullable=True),
        sa.Column("relevance_reasons", sa.JSON(), nullable=False),
        sa.Column("fit_reasons", sa.JSON(), nullable=False),
        sa.Column("scoring_version", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"], ["candidate_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_scores_candidate_profile_id"),
        "job_scores",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_job_scores_job_id"), "job_scores", ["job_id"], unique=False)
    op.create_index("ix_scores_job_created", "job_scores", ["job_id", "created_at"], unique=False)
    op.create_index(
        "ix_scores_relevance_fit",
        "job_scores",
        ["relevance_score", "candidate_fit_score"],
        unique=False,
    )
    op.create_table(
        "job_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("cleaned_text", sa.Text(), nullable=False),
        sa.Column("raw_html_compressed", sa.LargeBinary(), nullable=True),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("change_kind", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "content_hash", name="uq_snapshot_job_hash"),
    )
    op.create_index(op.f("ix_job_snapshots_job_id"), "job_snapshots", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_snapshots_job_id"), table_name="job_snapshots")
    op.drop_table("job_snapshots")
    op.drop_index("ix_scores_relevance_fit", table_name="job_scores")
    op.drop_index("ix_scores_job_created", table_name="job_scores")
    op.drop_index(op.f("ix_job_scores_job_id"), table_name="job_scores")
    op.drop_index(op.f("ix_job_scores_candidate_profile_id"), table_name="job_scores")
    op.drop_table("job_scores")
    op.drop_index(op.f("ix_feedback_events_job_id"), table_name="feedback_events")
    op.drop_table("feedback_events")
    op.drop_index(op.f("ix_application_records_status"), table_name="application_records")
    op.drop_index(op.f("ix_application_records_job_id"), table_name="application_records")
    op.drop_table("application_records")
    op.drop_index(
        op.f("ix_preference_profiles_candidate_profile_id"), table_name="preference_profiles"
    )
    op.drop_table("preference_profiles")
    op.drop_index("ix_jobs_state_city", table_name="job_postings")
    op.drop_index("ix_jobs_canonical_key", table_name="job_postings")
    op.drop_index("ix_jobs_active_published", table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_state"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_source_id"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_remote_type"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_published_at"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_employment_type"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_employer"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_contract_type"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_content_hash"), table_name="job_postings")
    op.drop_table("job_postings")
    op.drop_index("ix_crawl_runs_status_created", table_name="crawl_runs")
    op.drop_index(op.f("ix_crawl_runs_source_id"), table_name="crawl_runs")
    op.drop_table("crawl_runs")
    op.drop_table("sources")
    op.drop_table("candidate_profiles")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
